# This file seems to be needed only for bazel's dependency pinning to figure out
# declared dependencies, actual build rules are in BUILD.bazel.


[package]
name = "vello_deps"
edition = "2021"
version = "0.1.0"

[dependencies]
bytemuck = { version = "1.12.1", features = ["derive"] }
naga = { version = "0.13", features = ["wgsl-in", "msl-out", "validate"] }
peniko = { git = "https://github.com/linebender/peniko", rev = "cafdac9a211a0fb2fec5656bd663d1ac770bcc81" }
regex = "1.8.1"
thiserror = "1.0.40"

[lib]
