
###############################################################################
#
# THIS FILE IS AUTOGENERATED BY GYP_TO_ANDROID.PY. DO NOT EDIT.
#
# For bugs, please contact scroggo@google.com or djsollen@google.com
#
###############################################################################


###############################################################################
# 
# This file contains the shared and static dependencies needed by any target 
# that attempts to statically link Skia (i.e. libskia_static build target).
#
# This is a workaround for the fact that the build system does not add these
# transitive dependencies when it attempts to link libskia_static into another
# library.
#
###############################################################################
LOCAL_SHARED_LIBRARIES += \
	liblog \
	libGLESv2 \
	libEGL \
	libz \
	libexpat \
	libjpeg \
	libpng \
	libicuuc \
	libicui18n \
	libft2 \
	libdng_sdk \
	libpiex

LOCAL_STATIC_LIBRARIES += \
	libgif \
	libwebp-decode \
	libwebp-encode \
	libsfntly

