// DO NOT MODIFY! This file is autogenerated by gn_to_bp.py.
// If need to change a define, modify SkUserConfigManual.h
#ifndef SkUserConfig_DEFINED
#define SkUserConfig_DEFINED
#include "SkUserConfigManual.h"
  #define SK_ALLOW_STATIC_GLOBAL_INITIALIZERS 0
  #define SK_CODEC_DECODES_RAW
  #define SK_ENABLE_DISCRETE_GPU
  #define SK_GAMMA_APPLY_TO_A8
  #define SK_GAMMA_CONTRAST 0.0
  #define SK_GAMMA_EXPONENT 1.4
  #define SK_HAS_HEIF_LIBRARY
  #define SK_HAS_JPEG_LIBRARY
  #define SK_HAS_PNG_LIBRARY
  #define SK_HAS_WEBP_LIBRARY
  #define SK_PDF_USE_SFNTLY
  #define SK_SUPPORT_PDF
  #define SK_VULKAN
  #define SK_VULKAN_HEADER "Skia_Vulkan_Android.h"
  #define SK_XML
#endif//SkUserConfig_DEFINED
