#ifndef SkUserConfig_DEFINED
#define SkUserConfig_DEFINED

#define SK_FREETYPE_MINIMUM_RUNTIME_VERSION ((2 << 24) | (13 << 16) | (0 << 8))
#define SK_ALLOW_STATIC_GLOBAL_INITIALIZERS 0
#define SK_ENABLE_DISCRETE_GPU
#define SK_GAMMA_APPLY_TO_A8 1
#define SK_GAMMA_CONTRAST 0.0
#define SK_GAMMA_EXPONENT 1.4
#define SK_HAS_PNG_LIBRARY
#define SK_CODEC_DECODES_PNG 1
#define SK_ENCODE_PNG 1
#define SK_SAMPLES_FOR_X
#define SK_SUPPORT_GPU 0
#define SK_IGNORE_GPU_DITHER
#define SK_SUPPORT_DEPRECATED_CLIPOPS
#define SK_SUPPORT_LEGACY_DRAWLOOPER
#define SK_SUPPORT_LEGACY_CLIPTOLAYERFLAG
#define SK_SUPPORT_LEGACY_EMBOSSMASKFILTER
#define SK_SUPPORT_LEGACY_AA_CHOICE
#define SK_SUPPORT_LEGACY_AAA_CHOICE
#define SK_ENABLE_SKSL 1
#define SKIA_DLL
#define SK_RELEASE 1
#define SK_NDEBUG 1
#undef SK_DEBUG

#endif
