
###############################################################################
#
# THIS FILE IS AUTOGENERATED BY GYP_TO_ANDROID.PY. DO NOT EDIT.
#
###############################################################################

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_CFLAGS += \
	-fPIC \
	-Wno-c++11-extensions \
	-Wno-unused-parameter \
	-U_FORTIFY_SOURCE \
	-D_FORTIFY_SOURCE=1

LOCAL_CPPFLAGS := \
	-Wno-invalid-offsetof

LOCAL_SRC_FILES := \
	../bench/BenchLogger.cpp \
	../bench/ResultsWriter.cpp \
	PictureBenchmark.cpp \
	bench_pictures_main.cpp \
	timer/Timer.cpp \
	timer/TimerData.cpp \
	timer/GpuTimer.cpp \
	timer/SysTimer_posix.cpp \
	CrashHandler.cpp \
	flags/SkCommandLineFlags.cpp \
	image_expectations.cpp \
	LazyDecodeBitmap.cpp \
	PictureRenderer.cpp \
	PictureRenderingFlags.cpp \
	CopyTilesRenderer.cpp \
	../src/pipe/utils/SamplePipeControllers.cpp \
	picture_utils.cpp \
	../src/gpu/GrTest.cpp

LOCAL_SHARED_LIBRARIES := \
	liblog \
	libskia \
	libGLESv2 \
	libEGL

LOCAL_STATIC_LIBRARIES := \
	libjsoncpp

LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/../src/core \
	$(LOCAL_PATH)/../src/gpu \
	$(LOCAL_PATH)/../include/config \
	$(LOCAL_PATH)/../include/core \
	$(LOCAL_PATH)/../include/pathops \
	$(LOCAL_PATH)/../include/pipe \
	$(LOCAL_PATH)/../include/effects \
	$(LOCAL_PATH)/../include/images \
	$(LOCAL_PATH)/../include/ports \
	$(LOCAL_PATH)/../src/sfnt \
	$(LOCAL_PATH)/../include/utils \
	$(LOCAL_PATH)/../src/utils \
	$(LOCAL_PATH)/../include/gpu \
	$(LOCAL_PATH)/../src/images \
	$(LOCAL_PATH)/../src/lazy \
	$(LOCAL_PATH)/../src/pipe/utils \
	$(LOCAL_PATH)/flags \
	$(LOCAL_PATH)/../bench \
	$(LOCAL_PATH)/timer \
	$(LOCAL_PATH)/../third_party/externals/jsoncpp-chromium/overrides/include \
	$(LOCAL_PATH)/../third_party/externals/jsoncpp/include

LOCAL_MODULE_TAGS := \
	tests

LOCAL_MODULE := \
	skia_bench_pictures

include $(BUILD_NATIVE_TEST)
